In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
import numpy as np

In [3]:
!ls 'drive/My Drive/Hackathon/Hackathon/CreditScore/'

CreditScore_test.csv  CreditScore_train.csv


In [0]:
credit_train = pd.read_csv('drive/My Drive/Hackathon/Hackathon/CreditScore/CreditScore_train.csv')
credit_test = pd.read_csv('drive/My Drive/Hackathon/Hackathon/CreditScore/CreditScore_test.csv')

In [32]:
credit_train.shape

(80000, 305)

In [33]:
credit_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Columns: 305 entries, x001 to y
dtypes: float64(41), int64(264)
memory usage: 186.2 MB


In [34]:
credit_train.describe()

x001          x002  ...          x304             y
count  8.000000e+04  62815.000000  ...  14544.000000  80000.000000
mean   1.218319e+06    125.607307  ...      1.037589    619.397762
std    2.730146e+05    115.662548  ...      0.328551    118.357217
min    5.170000e+02      0.000000  ...      0.000000    300.000000
25%    9.745528e+05     32.000000  ...      0.975800    524.000000
50%    1.235833e+06    100.000000  ...      1.048700    599.000000
75%    1.445546e+06    180.000000  ...      1.185225    719.000000
max    1.677197e+06    718.000000  ...      5.156900    839.000000

[8 rows x 305 columns]

In [35]:
credit_train.head(5)

x001   x002  x003   x004   x005  x006  ...  x300  x301  x302  x303  x304    y
0  1084094  426.0  39.0  128.0  426.0     0  ...     0     0   NaN     0   NaN  807
1  1287777  160.0   2.0   64.0  160.0     1  ...     1     0   NaN     0   NaN  819
2  1483016  163.0  16.0  104.0  239.0     0  ...     0     0   NaN     0   NaN  803
3   959054    NaN   NaN    NaN  102.0     0  ...     1     0   NaN     0   NaN  530
4  1342113    3.0   2.0    2.0   62.0     0  ...     1     0   NaN     0   NaN  485

[5 rows x 305 columns]

In [36]:
rmv_null = []
for col in credit_train.columns:
  if (credit_train[col].isna().sum()/len(credit_train))*100 > 20:
    rmv_null.append(col)
print(rmv_null)

['x002', 'x003', 'x004', 'x041', 'x057', 'x058', 'x098', 'x148', 'x155', 'x162', 'x222', 'x223', 'x235', 'x237', 'x238', 'x239', 'x242', 'x253', 'x255', 'x256', 'x257', 'x259', 'x265', 'x266', 'x267', 'x268', 'x275', 'x287', 'x288', 'x289', 'x290', 'x293', 'x295', 'x297', 'x302', 'x304']


In [0]:
rmv_null.append('x001')

In [38]:
len(rmv_null)

37

In [0]:
credit_train.drop(columns=rmv_null,axis=1,inplace=True)
credit_test.drop(columns=rmv_null,axis=1,inplace=True)

In [0]:
unq_val = []
for col in credit_train.columns:
  if (credit_train[col].nunique()) == 1:
    unq_val.append(col)

In [0]:
credit_train.drop(columns=unq_val,axis=1,inplace=True)
credit_test.drop(columns=unq_val,axis=1,inplace=True)

In [42]:
for col in credit_train.columns:
   if credit_train[col].isna().sum() > 0:
     print(col,credit_train[col].isna().sum(),(credit_train[col].isna().sum()/len(credit_train))*100)

x005 4867 6.08375
x044 15753 19.69125
x045 15753 19.69125
x234 15316 19.145
x272 5752 7.19


In [0]:
for col in ['x005','x044','x045','x234','x272']:
  rpl = credit_train[col].mean()
  credit_train[col].fillna(rpl,inplace=True)

In [44]:
for col in credit_test.columns:
   if credit_test[col].isna().sum() > 0:
     print(col,credit_test[col].isna().sum(),(credit_test[col].isna().sum()/len(credit_test))*100)

x005 1243 6.215
x044 3921 19.605
x045 3921 19.605
x234 3794 18.970000000000002
x272 1437 7.185


In [0]:
for col in ['x005','x044','x045','x234','x272']:
  rpl = credit_test[col].mean()
  credit_test[col].fillna(rpl,inplace=True)

In [0]:
credit_train.corr()

x005      x006      x007  ...      x301      x303         y
x005  1.000000  0.120654 -0.057133  ... -0.096474 -0.011478  0.561643
x006  0.120654  1.000000 -0.128551  ... -0.005515 -0.009682  0.092552
x007 -0.057133 -0.128551  1.000000  ...  0.002983  0.091289  0.008623
x008 -0.071699 -0.111536  0.813488  ...  0.008644  0.104808 -0.022150
x009 -0.022244 -0.006926  0.268219  ...  0.015378  0.123830 -0.000553
x010  0.025753  0.023741  0.180121  ...  0.021424  0.138753  0.043540
x011  0.097916  0.055588  0.150105  ...  0.074808  0.211842  0.115146
x012  0.124923  0.057186  0.103993  ...  0.207981  0.274163  0.119120
x013  0.192119  0.066786  0.084077  ...  0.203118  0.275521  0.177954
x014  0.601528  0.121001  0.044111  ...  0.019913  0.166601  0.472186
x015  0.353557  0.076078  0.320414  ...  0.122583  0.304279  0.309319
x016  0.191201 -0.113815  0.460539  ...  0.077501  0.392175  0.193854
x017  0.361707  0.155161  0.184448  ...  0.119815  0.197701  0.303187
x018  0.396920  0.160862  0.229369  ...  0.023926  0.149123  0.409353
x019  0.325241 -0.074899  0.354662  ... -0.023316  0.202780  0.411619
x020  0.428496  0.083788  0.292127  ... -0.097379  0.052754  0.415614
x021  0.232651 -0.166315  0.477366  ... -0.066544  0.084721  0.242028
x022  0.455461  0.231601  0.217810  ... -0.105713  0.067454  0.568507
x023  0.362422 -0.136455  0.336537  ... -0.105558  0.070652  0.479607
x024 -0.005363  0.011274  0.212752  ...  0.333977  0.452565 -0.058331
x025  0.447964  0.089307  0.008108  ... -0.123933 -0.007029  0.485231
x026  0.180350  0.064332  0.134019  ... -0.000160  0.081729  0.214605
x027  0.295891  0.387572  0.209645  ... -0.058241  0.087665  0.426141
x028  0.372427  0.071073  0.006512  ... -0.104479 -0.007011  0.412992
x029  0.213022  0.045469  0.130500  ... -0.033425  0.068477  0.215034
x030  0.413070  0.082023  0.258383  ... -0.095691  0.049437  0.426534
x031 -0.197948 -0.008079  0.318792  ...  0.067877  0.066341 -0.280806
x032 -0.075092 -0.024816  0.177789  ...  0.028006  0.021886 -0.077139
x033 -0.105893 -0.035207  0.318809  ...  0.034102  0.029966 -0.113659
x034 -0.156448 -0.039830  0.427335  ...  0.045785  0.038631 -0.192863
...        ...       ...       ...  ...       ...       ...       ...
x262  0.387999  0.066064  0.015159  ... -0.111574 -0.001140  0.443585
x263  0.065558 -0.011583  0.190475  ... -0.000621  0.089727  0.134945
x264  0.070443 -0.023767  0.196525  ... -0.015050  0.078573  0.115324
x269  0.029014  0.004280  0.171136  ...  0.022610  0.090984  0.062783
x270  0.031850  0.006847  0.169570  ...  0.022127  0.090583  0.067566
x271  0.041343  0.011035  0.168085  ...  0.020255  0.091923  0.081103
x272 -0.038474 -0.001040 -0.010906  ... -0.011501  0.000053 -0.067494
x273  0.228328  0.025146  0.044566  ... -0.024636  0.160546  0.232838
x274  0.016843  0.050148 -0.013638  ...  0.069964  0.065323 -0.137094
x276 -0.077921  0.011387  0.070847  ...  0.214247  0.104461 -0.307033
x277 -0.076835  0.011555  0.068590  ...  0.213503  0.120531 -0.308404
x278 -0.077640  0.012116  0.058864  ...  0.215770  0.150214 -0.316125
x279  0.227829  0.021010  0.045543  ... -0.029538  0.159999  0.241753
x280  0.050463  0.024698 -0.000457  ...  0.056849  0.138658 -0.068942
x281  0.222372  0.014924  0.047390  ... -0.046489  0.127413  0.270083
x282  0.132207  0.127419  0.198799  ...  0.013869  0.104114  0.297065
x283  0.117310  0.132943  0.192746  ...  0.017817  0.100704  0.286920
x284  0.098882  0.143160  0.183520  ...  0.027067  0.095994  0.272008
x285 -0.054347 -0.014410  0.223212  ...  0.238893  0.572281 -0.059129
x286 -0.064191  0.029365 -0.000640  ...  0.261538  0.118638 -0.202854
x291  0.048810 -0.012181  0.149317  ...  0.160032  0.703851  0.046320
x292  0.205256  0.024236  0.044383  ... -0.022370  0.170384  0.233451
x294 -0.023020  0.021039  0.015570  ...  0.220346  0.435499 -0.149850
x296  0.061921 -0.021439  0.155772  ...  0.087249  0.592570  0.108856
x298 -0.066023 -0.008745  0.217392  ...  0.145912  0.241759 -0.044734
x299 -0.069295 -0.00

In [0]:
inp_cols = list(credit_train.columns)
inp_cols.remove('y')

In [47]:
print(inp_cols)

['x005', 'x006', 'x007', 'x008', 'x009', 'x010', 'x011', 'x012', 'x013', 'x014', 'x015', 'x016', 'x017', 'x018', 'x019', 'x020', 'x021', 'x022', 'x023', 'x024', 'x025', 'x026', 'x027', 'x028', 'x029', 'x030', 'x031', 'x032', 'x033', 'x034', 'x035', 'x036', 'x037', 'x038', 'x039', 'x040', 'x042', 'x043', 'x044', 'x045', 'x046', 'x047', 'x048', 'x049', 'x050', 'x051', 'x052', 'x053', 'x054', 'x055', 'x056', 'x059', 'x060', 'x061', 'x062', 'x063', 'x064', 'x065', 'x066', 'x068', 'x069', 'x070', 'x071', 'x072', 'x073', 'x074', 'x075', 'x076', 'x077', 'x078', 'x079', 'x080', 'x081', 'x082', 'x083', 'x084', 'x085', 'x086', 'x087', 'x088', 'x089', 'x090', 'x091', 'x092', 'x093', 'x097', 'x099', 'x100', 'x101', 'x102', 'x103', 'x104', 'x105', 'x106', 'x107', 'x108', 'x109', 'x110', 'x111', 'x112', 'x113', 'x114', 'x115', 'x116', 'x117', 'x118', 'x119', 'x120', 'x121', 'x122', 'x123', 'x124', 'x125', 'x126', 'x127', 'x128', 'x129', 'x130', 'x131', 'x132', 'x133', 'x134', 'x135', 'x136', 'x137',

In [48]:
cat_col = []
prt = []
i=0
for col in credit_train.columns:
  cnt = credit_train[col].nunique()
  if cnt > 2 and cnt < 20:
    print(col,i,cnt)
    cat_col.append(i)
    prt.append(col)
  i = i + 1

x018 13 17
x019 14 12
x022 17 7
x023 18 6
x037 32 5
x038 33 11
x039 34 17
x046 40 19
x047 41 11
x048 42 11
x049 43 9
x050 44 8
x051 45 8
x052 46 8
x053 47 9
x054 48 11
x055 49 17
x061 53 15
x068 59 7
x069 60 14
x077 68 3
x078 69 5
x079 70 9
x080 71 17
x100 87 13
x101 88 13
x102 89 19
x107 94 10
x108 95 13
x112 99 17
x122 109 15
x123 110 19
x156 141 10
x163 147 11
x169 153 16
x174 158 19
x175 159 11
x176 160 13
x177 161 16
x178 162 17
x179 163 18
x182 166 15
x183 167 18
x227 209 19
x228 210 13
x229 211 11
x241 219 18
x251 228 15
x252 229 4
x254 230 15


In [49]:
credit_train[prt].apply(lambda x: print(x.unique()))

[ 8  5  4  2  6  3  7  1  0 10  9 12 11 13 16 15 14]
[ 5  3  2  0  1  4  6  7  8  9 10 11]
[3 0 1 2 4 5 6]
[2 1 0 3 4 5]
[0 1 4 2 3]
[ 0  1  3  2  4  5  6  7  9  8 10]
[ 0  1  2  4  3  6  9  5  8  7 10 13 14 11 12 16 15]
[ 2  1  0  3  4  7  5  6 11 10  9  8 13 14 12 16 17 15 25]
[ 0  1  5  3  2  4  6  7  8  9 10]
[ 0  1  2  3  4  5  8  6  7  9 12]
[0 1 3 5 2 4 6 7 9]
[0 1 2 3 4 6 5 7]
[0 1 2 3 6 4 5 7]
[0 2 1 3 5 4 7 6]
[0 4 1 2 3 7 5 6 8]
[ 0  1  2  3  4  5  6  8  7 10  9]
[ 1  0  2  4  3  5  7  8 10  6 11  9 17 13 12 14 15]
[ 0  1  2  8  4  3  6  5  7 16  9 13 10 22 11]
[0 1 3 2 5 8 4]
[ 0  1  2  3  4 11  5  6  8 15  9  7 13 10]
[0 1 2]
[0 1 2 3 6]
[ 0  1  2  3  4 20  5 11  6]
[ 0  1  2  3  5  4  8  6  7 21 17 14 10 15  9 19 20]
[ 0  1  2 10  6  3  4  5  7 11  8 16 19]
[ 0  1 11  3  2  5  4  6  8 10  7 12  9]
[ 0  1  4  2  6  3  8 14 10  5 11 16  7 13 12 17 27  9 18]
[0 2 1 4 3 5 7 8 6 9]
[ 0  1  2  6 11  3  5  4  9  7 10  8 14]
[ 0  1  2  3  4  6  5 15  9  8  7 12 11 10 14 13 16]
[ 

x018    None
x019    None
x022    None
x023    None
x037    None
x038    None
x039    None
x046    None
x047    None
x048    None
x049    None
x050    None
x051    None
x052    None
x053    None
x054    None
x055    None
x061    None
x068    None
x069    None
x077    None
x078    None
x079    None
x080    None
x100    None
x101    None
x102    None
x107    None
x108    None
x112    None
x122    None
x123    None
x156    None
x163    None
x169    None
x174    None
x175    None
x176    None
x177    None
x178    None
x179    None
x182    None
x183    None
x227    None
x228    None
x229    None
x241    None
x251    None
x252    None
x254    None
dtype: object

In [50]:
credit_test[prt].apply(lambda x: print(x.unique()))

[ 3  6  4  0  2  5  7  8  1  9 12 11 10 13]
[ 1  4  0  3  2  5  6  7  8  9 11 10]
[2 3 1 0 4 5]
[1 3 2 0 4 5]
[0 1 3 2 4]
[ 0  1  4  2  3  5 13  6  7  9]
[ 0  1  2  6  4  3  5  7 10  8 20  9 11 12 13]
[ 0  1  3  5  2  4  6  8  7 13 11  9 12]
[0 1 2 3 4 5 8 6 7]
[0 1 2 3 5 4 7]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5]
[0 1 2 6 3 4 5]
[0 1 2 4 3 5 7]
[0 1 2 3 4 5 8]
[0 1 2 4 6 3 5 7]
[ 0  3  1  5  2  4  7 10  6 14 11  8  9]
[ 0  1  2  3  4 14  9  8  5  7  6]
[0 1 4 2 3]
[ 0  1  4  2  6  3  5 14  7]
[0 1 3 2]
[0 1 2 3 5]
[0 1 3 6 2 4 5]
[ 0  1  2  3  4  6  8  7  5  9 24]
[ 0  1  2  4  3  5  6 10  7]
[0 1 2 5 3 4 6]
[ 0  2  5  1  3  6  4 10 14  7 12]
[0 1 2 3 5 4 7 6]
[ 0  2  1  4  3  5  6  8 12]
[ 0  2  1  7  3  4  5  6  8  9 10 12]
[ 4  0  2  3  1  7  5  6 12]
[ 4  0  3  6  1  2  5  7 10  8 12 13  9]
[0 6 4 2 1 3 7 5 8]
[0 3 4 1 2 5 7 6]
[ 1  0  4  8  3  2 15  6  7  5 10 14 12  9 24 19]
[ 1  0  2  5  4  3  6 17  8  7  9 10 11 15 13]
[ 0  1  3  5  2  6  4  7  8 10 13]
[ 0  1  2  3  5  6  4  7  9  8 

x018    None
x019    None
x022    None
x023    None
x037    None
x038    None
x039    None
x046    None
x047    None
x048    None
x049    None
x050    None
x051    None
x052    None
x053    None
x054    None
x055    None
x061    None
x068    None
x069    None
x077    None
x078    None
x079    None
x080    None
x100    None
x101    None
x102    None
x107    None
x108    None
x112    None
x122    None
x123    None
x156    None
x163    None
x169    None
x174    None
x175    None
x176    None
x177    None
x178    None
x179    None
x182    None
x183    None
x227    None
x228    None
x229    None
x241    None
x251    None
x252    None
x254    None
dtype: object

In [0]:
credit_train['src'] = 0
credit_test['src'] = 1

In [0]:
src = pd.concat([credit_train,credit_test])

In [0]:
src = pd.get_dummies(data=src, columns=prt)

In [0]:
train = src[src['src'] == 0]
test = src[src['src'] == 1]

In [0]:
inp_cols = list(train.columns)
inp_cols.remove('y')
X_train = train[inp_cols]
Y_train = train['y']
X_test = test[inp_cols]
Y_test = test['y']

In [56]:
print(X_train.shape)
print(X_test.shape)

(80000, 866)
(20000, 866)


In [57]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
sel = RandomForestRegressor(n_estimators = 100,random_state=0,n_jobs=-1)
sel.fit(X_train, Y_train)
print(sel.feature_importances_)

[1.35158210e-02 7.72986429e-03 7.03937215e-04 1.24874135e-03
 6.91185036e-04 6.07643014e-04 7.81559497e-04 6.86166496e-04
 7.59897067e-04 6.86196115e-03 2.12750786e-03 7.03421048e-04
 1.83668164e-03 1.93324841e-03 1.18284233e-03 1.11237539e-03
 3.66145782e-04 1.30708084e-04 8.77453976e-05 5.02266292e-04
 5.70210109e-04 1.00015754e-03 4.38139706e-03 1.84205277e-04
 3.33353519e-04 6.21870477e-04 1.31431459e-03 4.96925501e-03
 1.92098040e-03 1.40433382e-03 5.13174774e-01 2.76704451e-02
 1.62437499e-03 5.52631801e-02 2.26694014e-03 5.52854241e-08
 2.42060634e-04 4.52002879e-04 7.41659462e-04 1.36090237e-03
 1.49873503e-04 6.53687742e-05 9.99244443e-05 1.12867540e-04
 5.28740167e-04 1.10215289e-04 7.73960298e-02 4.38850442e-03
 4.39396507e-04 1.05453459e-03 3.24583741e-05 1.73774539e-05
 8.19912184e-05 1.83941718e-04 1.25708773e-04 2.41769273e-04
 1.18829497e-04 3.19659634e-05 8.06162286e-05 4.96650234e-05
 4.35975896e-06 3.85756688e-04 1.19057996e-02 2.05987727e-05
 5.08896389e-04 6.985435

In [0]:
imp = sel.feature_importances_

In [59]:
cntr = 0
pos = []
idx = 0
for value in imp:
  if round(value*1000,4) > 0.05:
    cntr = cntr+1
    pos.append(idx)
  idx = idx + 1
  
print(pos)
print(cntr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 52, 53, 54, 55, 56, 58, 61, 62, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 81, 82, 83, 84, 85, 86, 88, 89, 96, 101, 102, 103, 104, 105, 106, 107, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 215, 216, 217, 218, 219, 220, 221, 231, 232, 233, 234, 235, 243, 244, 245, 246, 251, 252, 256, 257, 261, 262, 263, 273, 274, 275, 276, 291, 292, 293, 310, 311, 321, 322, 332, 333, 341,

In [0]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [0]:
X_train = X_train.iloc[:,pos]
X_test = X_test.iloc[:,pos]

In [0]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, r2_score

In [0]:
from sklearn import preprocessing
X_train = preprocessing.StandardScaler().fit(X_train).transform(X_train.astype(float))
X_test = preprocessing.StandardScaler().fit(X_test).transform(X_test.astype(float))

In [64]:
X_train.shape

(80000, 258)

In [65]:
from sklearn.linear_model import LinearRegression  
lm = LinearRegression()
lm.fit(X_train,Y_train)
Y_train_predict = lm.predict(X_train)
Y_test_predict = lm.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 47.25481600436747
RMSE Test: 82158116283.14641
MAE Train 35.86535422053743
MAE Test 32877578365.387894


**SVR taking more time -- Need more time to work on SVR**

In [0]:
from sklearn.svm import SVR
SVR = SVR(kernel='linear')
SVR.fit(X_train,Y_train)
Y_train_predict = SVR.predict(X_train)
Y_test_predict = SVR.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))

In [66]:
from sklearn.linear_model import Ridge
ridgeReg = Ridge(alpha=0.005, normalize=False)
ridgeReg.fit(X_train,Y_train)
Y_train_predict = ridgeReg.predict(X_train)
Y_test_predict = ridgeReg.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 47.254811686727486
RMSE Test: 47.59032348036024
MAE Train 35.86529512295356
MAE Test 36.15786746093748


In [67]:
from sklearn.linear_model import Lasso
lassoReg = Lasso(alpha=0.005, normalize=False,max_iter=10000)
lassoReg.fit(X_train,Y_train)
Y_train_predict = lassoReg.predict(X_train)
Y_test_predict = lassoReg.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 47.257194065226024
RMSE Test: 47.58866806777989
MAE Train 35.86621084175961
MAE Test 36.15086349017317


In [68]:
from sklearn.linear_model import ElasticNet
ENreg = ElasticNet(alpha=1, l1_ratio=1, normalize=False)
ENreg.fit(X_train,Y_train)
Y_train_predict = ENreg.predict(X_train)
Y_test_predict = ENreg.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 48.89680288128976
RMSE Test: 48.936787871993616
MAE Train 37.45847399363772
MAE Test 37.54676560034041


In [69]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
sel = RandomForestRegressor()
sel.fit(X_train, Y_train)
Y_train_predict = sel.predict(X_train)
Y_test_predict = sel.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 13.33487136545881
RMSE Test: 69.26015168912063
MAE Train 8.839799166666667
MAE Test 56.5784


In [71]:
for i in range(1, 20):
    print('Accuracy score using max_depth =', i, end = ': ')
    sel = RandomForestRegressor(max_depth=i)
    sel.fit(X_train, Y_train)
    Y_train_predict = sel.predict(X_train)
    Y_test_predict = sel.predict(X_test)
    print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
    print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
    print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
    print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Accuracy score using max_depth = 1: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 82.98164313375112
RMSE Test: 158.65197383922776
MAE Train 65.80251631083267
MAE Test 135.81828286505197
Accuracy score using max_depth = 2: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 70.4806840333889
RMSE Test: 127.13987616422885
MAE Train 55.34538162485878
MAE Test 105.89306905137708
Accuracy score using max_depth = 3: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 60.619059194395824
RMSE Test: 122.77728472961722
MAE Train 47.87418304919869
MAE Test 100.05329019469748
Accuracy score using max_depth = 4: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 53.95908320856154
RMSE Test: 123.14403951450055
MAE Train 41.57198763757245
MAE Test 94.99059201331613
Accuracy score using max_depth = 5: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 49.70354946847811
RMSE Test: 131.5353147048945
MAE Train 37.98979987010732
MAE Test 94.7272025206701
Accuracy score using max_depth = 6: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 44.77900661247074
RMSE Test: 108.34857129144048
MAE Train 33.945666536441024
MAE Test 79.23044830086943
Accuracy score using max_depth = 7: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.76336133522666
RMSE Test: 100.59559445171146
MAE Train 30.679080190796704
MAE Test 72.10895853252102
Accuracy score using max_depth = 8: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 37.14297804610055
RMSE Test: 84.86035655643838
MAE Train 27.746334156293557
MAE Test 62.68249113055733
Accuracy score using max_depth = 9: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 34.166668040007494
RMSE Test: 67.75106882929965
MAE Train 25.51224377899418
MAE Test 55.215544386125
Accuracy score using max_depth = 10: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 31.758794492020463
RMSE Test: 78.21831042464437
MAE Train 23.601657898196947
MAE Test 61.09238713101624
Accuracy score using max_depth = 11: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.02122507346449
RMSE Test: 68.52665894928612
MAE Train 21.520954348345146
MAE Test 55.04291158445893
Accuracy score using max_depth = 12: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 26.391432862947404
RMSE Test: 65.92693188557273
MAE Train 19.54516172354119
MAE Test 53.61659369518326
Accuracy score using max_depth = 13: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 24.07245058695939
RMSE Test: 66.90005073568769
MAE Train 17.82034545787163
MAE Test 54.28221586085047
Accuracy score using max_depth = 14: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 21.896740571401256
RMSE Test: 66.75523222438203
MAE Train 16.141887790225034
MAE Test 53.887451578990614
Accuracy score using max_depth = 15: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 20.051099830681114
RMSE Test: 64.3381088267368
MAE Train 14.738528752517373
MAE Test 52.2102706179883
Accuracy score using max_depth = 16: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 18.323103770355026
RMSE Test: 62.76682064279442
MAE Train 13.36696520728633
MAE Test 51.37929730174114
Accuracy score using max_depth = 17: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 17.100509520793572
RMSE Test: 68.74412027489791
MAE Train 12.433681485346893
MAE Test 55.67647525672614
Accuracy score using max_depth = 18: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 16.163610107323883
RMSE Test: 67.64755682996653
MAE Train 11.659150951771396
MAE Test 54.58306411508367
Accuracy score using max_depth = 19: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 15.214702546010662
RMSE Test: 67.0555443914206
MAE Train 10.894427661630209
MAE Test 54.40624679064379


In [72]:
for i in ['auto','sqrt','log2',0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]:
    print('Accuracy score using max_features =', i, end = ': ')
    sel = RandomForestRegressor(max_depth=9,max_features=i)
    sel.fit(X_train, Y_train)
    Y_train_predict = sel.predict(X_train)
    Y_test_predict = sel.predict(X_test)
    print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
    print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
    print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
    print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Accuracy score using max_features = auto: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 34.36311802873383
RMSE Test: 71.93383610884815
MAE Train 25.56149095170005
MAE Test 56.84083574092982
Accuracy score using max_features = sqrt: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 37.12738579467248
RMSE Test: 47.76357073856844
MAE Train 28.890092884489633
MAE Test 37.8176689917381
Accuracy score using max_features = log2: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.289232011731755
RMSE Test: 46.15993685568003
MAE Train 31.5646591601111
MAE Test 36.522398128203946
Accuracy score using max_features = 0.1: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 35.09688296675614
RMSE Test: 46.438415897925296
MAE Train 26.965609884351572
MAE Test 36.94746845377843
Accuracy score using max_features = 0.2: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.83010256696659
RMSE Test: 53.81306010485343
MAE Train 25.682881733125047
MAE Test 44.118277902316485
Accuracy score using max_features = 0.3: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.42681327594995
RMSE Test: 47.27149047773751
MAE Train 25.232432049726
MAE Test 38.20549218255773
Accuracy score using max_features = 0.4: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.280171399155
RMSE Test: 51.97110080120083
MAE Train 25.0410732026703
MAE Test 42.92119621196098
Accuracy score using max_features = 0.5: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.00627246267801
RMSE Test: 58.65061222162094
MAE Train 24.684644708354732
MAE Test 47.49539913066198
Accuracy score using max_features = 0.6: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.19052475026049
RMSE Test: 53.10034313408207
MAE Train 24.851000274432806
MAE Test 43.468619869065506
Accuracy score using max_features = 0.7: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.46785545717393
RMSE Test: 61.638976867844036
MAE Train 25.029953739108688
MAE Test 50.69395552934066
Accuracy score using max_features = 0.8: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.58302964793894
RMSE Test: 57.68017490673391
MAE Train 25.083963803719314
MAE Test 46.76254031273875
Accuracy score using max_features = 0.9: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 33.9304679205708
RMSE Test: 69.79592473698806
MAE Train 25.32782373263032
MAE Test 54.59931425618395
Accuracy score using max_features = 1.0: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 34.14241240242107
RMSE Test: 68.12348251636145
MAE Train 25.465897350483377
MAE Test 55.21922150929988


In [73]:
for i in range(2, 10):
    print('Accuracy score using min_samples_split =', i, end = ': ')
    sel = RandomForestRegressor(max_depth=9,max_features='log2',min_samples_split=i)
    sel.fit(X_train, Y_train)
    Y_train_predict = sel.predict(X_train)
    Y_test_predict = sel.predict(X_test)
    print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
    print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
    print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
    print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Accuracy score using min_samples_split = 2: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.19204367815167
RMSE Test: 50.10015376911857
MAE Train 31.318931897278233
MAE Test 40.75746538687997
Accuracy score using min_samples_split = 3: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.39415707150725
RMSE Test: 45.98440796106755
MAE Train 31.778040115961748
MAE Test 37.01191865234804
Accuracy score using min_samples_split = 4: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 41.280765358764285
RMSE Test: 49.385374214607
MAE Train 32.33954728270123
MAE Test 39.97755986315363
Accuracy score using min_samples_split = 5: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.71304845908081
RMSE Test: 48.28537301473834
MAE Train 31.96336504931203
MAE Test 38.77946391166923
Accuracy score using min_samples_split = 6: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.86879704654616
RMSE Test: 61.652341000196394
MAE Train 32.19655791043152
MAE Test 49.74661491919126
Accuracy score using min_samples_split = 7: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 41.16769895612603
RMSE Test: 48.550232361628844
MAE Train 32.24824089840785
MAE Test 39.057116870205185
Accuracy score using min_samples_split = 8: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 41.12403055962998
RMSE Test: 50.08529204864931
MAE Train 32.15434867876244
MAE Test 39.93287354983896
Accuracy score using min_samples_split = 9: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 41.15977852668907
RMSE Test: 48.68329039252815
MAE Train 32.11677098371017
MAE Test 39.32147831938163


In [74]:
sel = RandomForestRegressor(max_depth=9,max_features='log2',min_samples_split=3)
sel.fit(X_train, Y_train)
Y_train_predict = sel.predict(X_train)
Y_test_predict = sel.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 40.645100277668746
RMSE Test: 47.37098072049261
MAE Train 31.853188864516433
MAE Test 37.469735309876484


In [75]:
from sklearn.tree import DecisionTreeRegressor
sel = DecisionTreeRegressor(max_depth=9,max_features='log2',min_samples_split=3)
sel.fit(X_train, Y_train)
Y_train_predict = sel.predict(X_train)
Y_test_predict = sel.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 49.37631421661534
RMSE Test: 51.34508980115088
MAE Train 37.53542189190631
MAE Test 38.97382982132914


In [76]:
for i in range(1, 20):
    print('Accuracy score using max_depth =', i, end = ': ')
    sel = DecisionTreeRegressor(max_depth=i)
    sel.fit(X_train, Y_train)
    Y_train_predict = sel.predict(X_train)
    Y_test_predict = sel.predict(X_test)
    print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
    print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
    print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
    print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Accuracy score using max_depth = 1: RMSE Train: 83.05632153082902
RMSE Test: 158.77615609762253
MAE Train 65.86446828429173
MAE Test 135.91127069314484
Accuracy score using max_depth = 2: RMSE Train: 71.606242802551
RMSE Test: 139.6362573879753
MAE Train 56.114337833710735
MAE Test 113.57725660477185
Accuracy score using max_depth = 3: RMSE Train: 62.2973877375949
RMSE Test: 140.68449379183383
MAE Train 49.26315498125455
MAE Test 109.28649186705023
Accuracy score using max_depth = 4: RMSE Train: 55.23033784270376
RMSE Test: 138.99973640738762
MAE Train 42.39901744851984
MAE Test 103.91157579349203
Accuracy score using max_depth = 5: RMSE Train: 50.695010537549976
RMSE Test: 131.1419017479636
MAE Train 38.75939663965641
MAE Test 94.23706094816785
Accuracy score using max_depth = 6: RMSE Train: 46.65345593732337
RMSE Test: 125.22838425274722
MAE Train 35.43833267403835
MAE Test 88.42451835958003
Accuracy score using max_depth = 7: RMSE Train: 43.25345589252027
RMSE Test: 115.938861046169

In [77]:
for i in ['auto','sqrt','log2',0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]:
    print('Accuracy score using max_features =', i, end = ': ')
    sel = DecisionTreeRegressor(max_depth=11,max_features=i)
    sel.fit(X_train, Y_train)
    Y_train_predict = sel.predict(X_train)
    Y_test_predict = sel.predict(X_test)
    print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
    print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
    print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
    print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Accuracy score using max_features = auto: RMSE Train: 32.330779244409676
RMSE Test: 71.86829682696415
MAE Train 23.735651707156286
MAE Test 56.66430435467503
Accuracy score using max_features = sqrt: RMSE Train: 43.662395838852795
RMSE Test: 55.284494440421916
MAE Train 32.572156605672404
MAE Test 42.074889702276884
Accuracy score using max_features = log2: RMSE Train: 45.360253201130256
RMSE Test: 72.46362158703498
MAE Train 34.16711708715005
MAE Test 58.56720607223022
Accuracy score using max_features = 0.1: RMSE Train: 40.22440057075747
RMSE Test: 79.42015940878318
MAE Train 30.03684667240898
MAE Test 61.119442897727176
Accuracy score using max_features = 0.2: RMSE Train: 35.659780968852836
RMSE Test: 51.934011410605635
MAE Train 26.28266000238555
MAE Test 38.14598532170183
Accuracy score using max_features = 0.3: RMSE Train: 33.59821494937197
RMSE Test: 71.45623034119282
MAE Train 24.77369406493457
MAE Test 58.12027407232709
Accuracy score using max_features = 0.4: RMSE Train: 33.7

In [78]:
for i in range(2, 10):
    print('Accuracy score using min_samples_split =', i, end = ': ')
    sel = RandomForestRegressor(max_depth=11,max_features=0.2,min_samples_split=i)
    sel.fit(X_train, Y_train)
    Y_train_predict = sel.predict(X_train)
    Y_test_predict = sel.predict(X_test)
    print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
    print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
    print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
    print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Accuracy score using min_samples_split = 2: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.05709994105393
RMSE Test: 52.81421184616992
MAE Train 21.89979945889583
MAE Test 42.65906138248346
Accuracy score using min_samples_split = 3: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.44255463177091
RMSE Test: 51.312312394089275
MAE Train 22.132828094782543
MAE Test 41.892657721124344
Accuracy score using min_samples_split = 4: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.414582051193424
RMSE Test: 53.394934076015105
MAE Train 22.160024884979872
MAE Test 42.6733615151681
Accuracy score using min_samples_split = 5: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.11780617018469
RMSE Test: 53.28395320154676
MAE Train 21.89312523708856
MAE Test 44.134917542016346
Accuracy score using min_samples_split = 6: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.230650670825742
RMSE Test: 45.2841206212861
MAE Train 22.023262154144103
MAE Test 37.13236329873734
Accuracy score using min_samples_split = 7: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.26615318865599
RMSE Test: 51.52964949176109
MAE Train 22.023794124993955
MAE Test 42.05626726284633
Accuracy score using min_samples_split = 8: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.578091116140552
RMSE Test: 50.94548998129151
MAE Train 22.264582229030136
MAE Test 41.72635425551988
Accuracy score using min_samples_split = 9: 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RMSE Train: 29.731228082079944
RMSE Test: 44.62818082705415
MAE Train 22.496661647696456
MAE Test 35.9983077676493


In [83]:
sel = RandomForestRegressor(n_estimators=50,max_depth=11,max_features=0.2,min_samples_split=4)
sel.fit(X_train, Y_train)
Y_train_predict = sel.predict(X_train)
Y_test_predict = sel.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 28.44600119406806
RMSE Test: 46.59393633303935
MAE Train 21.49316376849436
MAE Test 38.227480622931964


In [0]:
from sklearn.neighbors import KNeighborsRegressor
accuracy_dict = {}
accuracy_list = []
for K in range(0,25,5):
    K_value = K + 1
    neigh = KNeighborsRegressor(n_neighbors=K_value,weights='uniform',algorithm='auto')
    neigh.fit(X_train, Y_train)
    y_pred=neigh.predict(X_test)
    accuracy = r2_score(Y_test, y_pred)
    accuracy_dict.update({K_value:accuracy})
    accuracy_list.append(accuracy)
    print("RMSE is",np.sqrt(mean_squared_error(Y_test, y_pred)),"% for K-Value",K_value)

**FNN**

In [84]:
from keras.models import Sequential
from keras import optimizers
from keras.layers import Activation, Dense
from keras.layers import Dropout
from keras.layers import BatchNormalization


Using TensorFlow backend.


In [0]:
def mlp_model():
    model = Sequential()
    
    model.add(Dense(50, input_shape = (X_train.shape[1], )))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(50))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(50))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(50))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(1))
    
    adam = optimizers.Adam(lr = 0.001)
    model.compile(optimizer = adam, loss = 'mean_squared_error', metrics=['mse'])
    
    return model

In [92]:
model = mlp_model()
history = model.fit(X_train, Y_train, validation_split = 0.2, epochs = 100, verbose = 1)

Train on 64000 samples, validate on 16000 samples
Epoch 1/100
64000/64000 [==============================] - 9s 137us/step - loss: 267136.4248 - mean_squared_error: 267136.4248 - val_loss: 98034.2414 - val_mean_squared_error: 98034.2414
Epoch 2/100
64000/64000 [==============================] - 7s 105us/step - loss: 42490.9516 - mean_squared_error: 42490.9516 - val_loss: 11280.2963 - val_mean_squared_error: 11280.2963
Epoch 3/100
64000/64000 [==============================] - 7s 105us/step - loss: 6826.2281 - mean_squared_error: 6826.2281 - val_loss: 12635.2032 - val_mean_squared_error: 12635.2032
Epoch 4/100
64000/64000 [==============================] - 7s 104us/step - loss: 6016.7378 - mean_squared_error: 6016.7378 - val_loss: 5336.2321 - val_mean_squared_error: 5336.2321
Epoch 5/100
64000/64000 [==============================] - 7s 103us/step - loss: 5634.6609 - mean_squared_error: 5634.6609 - val_loss: 5956.6071 - val_mean_squared_error: 5956.6071
Epoch 6/100
64000/64000 [========

In [93]:
results = model.evaluate(X_test, Y_test)

20000/20000 [==============================] - 1s 31us/step


In [94]:
print(model.metrics_names)     # list of metric names the model is employing
print(results)   

['loss', 'mean_squared_error']
[1218.6957916015624, 1218.6957916015624]


In [95]:
print('loss: ', results[0])
print('mse: ', results[1])

loss:  1218.6957916015624
mse:  1218.6957916015624


**FNN - RMSE = 34.90**

In [96]:
print('RMSE:',np.sqrt(results[1]))

RMSE: 34.90982371198059


**FNN with Voting Classifier - Stacking**

In [104]:
from sklearn.ensemble import VotingRegressor
from keras.wrappers.scikit_learn import KerasRegressor
# create 5 models to ensemble
model1 = KerasRegressor(build_fn = mlp_model, epochs = 100, batch_size = 400)
model2 = KerasRegressor(build_fn = mlp_model, epochs = 80, batch_size = 200)
model3 = KerasRegressor(build_fn = mlp_model, epochs = 70, batch_size = 100)
model4 = KerasRegressor(build_fn = mlp_model, epochs = 90, batch_size = 180)
model5 = KerasRegressor(build_fn = mlp_model, epochs = 110, batch_size = 500)
ensemble_clf = VotingRegressor(estimators = [('model1', model1), ('model2', model2), ('model3', model3), ('model4', model4), ('model5', model5)])
ensemble_clf.fit(X_train, Y_train)
Y_train_predict = ensemble_clf.predict(X_train)
Y_test_predict = ensemble_clf.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Epoch 1/100
80000/80000 [==============================] - 6s 77us/step - loss: 393318.2744 - mean_squared_error: 393318.2744
Epoch 2/100
80000/80000 [==============================] - 2s 29us/step - loss: 379572.9873 - mean_squared_error: 379572.9873
Epoch 3/100
80000/80000 [==============================] - 2s 28us/step - loss: 356222.0872 - mean_squared_error: 356222.0872
Epoch 4/100
80000/80000 [==============================] - 2s 29us/step - loss: 325853.3241 - mean_squared_error: 325853.3241
Epoch 5/100
80000/80000 [==============================] - 2s 28us/step - loss: 291546.2977 - mean_squared_error: 291546.2977
Epoch 6/100
80000/80000 [==============================] - 2s 28us/step - loss: 255723.1884 - mean_squared_error: 255723.1884
Epoch 7/100
80000/80000 [==============================] - 2s 27us/step - loss: 219952.2481 - mean_squared_error: 219952.2481
Epoch 8/100
80000/80000 [==============================] - 2s 28us/step - loss: 185866.7455 - mean_squared_error: 1858

**FNN - Best Result = 30.34**

In [105]:
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 29.042400319948936
RMSE Test: 30.345744618511404
MAE Train 22.172668452072145
MAE Test 23.043512438964843


In [101]:
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 30.17894909942326
RMSE Test: 31.025798867845705
MAE Train 23.151327069091796
MAE Test 23.696060331726073


**RNN**

In [0]:
from keras.layers import LSTM, Bidirectional
from keras.wrappers.scikit_learn import KerasRegressor

def deep_bidirectional_lstm():
    model = Sequential()
    model.add(Bidirectional(LSTM(10, return_sequences = True), input_shape = (258,1)))
    model.add(Bidirectional(LSTM(9, return_sequences = True)))
    model.add(Bidirectional(LSTM(11, return_sequences = True)))
    model.add(Bidirectional(LSTM(10, return_sequences = False)))
    model.add(Dense(60))
    model.add(Activation('elu'))
    model.add(Dense(1))
    
    adam = optimizers.Adam(lr = 0.001)
    model.compile(optimizer = adam, loss = 'mean_squared_error', metrics=['mse'])
    
    return model

In [0]:
X_train = np.array(X_train).reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = np.array(X_test).reshape((X_test.shape[0], X_test.shape[1], 1))

In [116]:
model = KerasRegressor(build_fn = deep_bidirectional_lstm, epochs = 20, batch_size = 1000, verbose = 1)
model.fit(X_train, Y_train)

Epoch 1/20
80000/80000 [==============================] - 194s 2ms/step - loss: 388787.6937 - mean_squared_error: 388787.6937
Epoch 2/20
80000/80000 [==============================] - 179s 2ms/step - loss: 344501.6703 - mean_squared_error: 344501.6703
Epoch 3/20
80000/80000 [==============================] - 179s 2ms/step - loss: 285074.2541 - mean_squared_error: 285074.2541
Epoch 4/20
80000/80000 [==============================] - 180s 2ms/step - loss: 218390.1143 - mean_squared_error: 218390.1143
Epoch 5/20
80000/80000 [==============================] - 182s 2ms/step - loss: 153118.0095 - mean_squared_error: 153118.0095
Epoch 6/20
80000/80000 [==============================] - 179s 2ms/step - loss: 97933.6140 - mean_squared_error: 97933.6140
Epoch 7/20
80000/80000 [==============================] - 179s 2ms/step - loss: 57982.9823 - mean_squared_error: 57982.9823
Epoch 8/20
80000/80000 [==============================] - 179s 2ms/step - loss: 33646.4969 - mean_squared_error: 33646.496

In [117]:
Y_train_predict = model.predict(X_train)
Y_test_predict = model.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

20000/20000 [==============================] - 11s 569us/step
RMSE Train: 118.35648217615457
RMSE Test: 118.88097524879714
MAE Train 101.38889569091796
MAE Test 101.95999301757813
