In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np

In [3]:
!ls 'drive/My Drive/Hackathon/Hackathon/CreditScore/'

CreditScore_test.csv  CreditScore_train.csv


In [0]:
credit_train = pd.read_csv('drive/My Drive/Hackathon/Hackathon/CreditScore/CreditScore_train.csv')
credit_test = pd.read_csv('drive/My Drive/Hackathon/Hackathon/CreditScore/CreditScore_test.csv')

In [5]:
credit_train.shape

(80000, 305)

In [6]:
credit_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Columns: 305 entries, x001 to y
dtypes: float64(41), int64(264)
memory usage: 186.2 MB


In [7]:
credit_train.describe()

x001          x002  ...          x304             y
count  8.000000e+04  62815.000000  ...  14544.000000  80000.000000
mean   1.218319e+06    125.607307  ...      1.037589    619.397762
std    2.730146e+05    115.662548  ...      0.328551    118.357217
min    5.170000e+02      0.000000  ...      0.000000    300.000000
25%    9.745528e+05     32.000000  ...      0.975800    524.000000
50%    1.235833e+06    100.000000  ...      1.048700    599.000000
75%    1.445546e+06    180.000000  ...      1.185225    719.000000
max    1.677197e+06    718.000000  ...      5.156900    839.000000

[8 rows x 305 columns]

In [8]:
credit_train.head(5)

x001   x002  x003   x004   x005  x006  ...  x300  x301  x302  x303  x304    y
0  1084094  426.0  39.0  128.0  426.0     0  ...     0     0   NaN     0   NaN  807
1  1287777  160.0   2.0   64.0  160.0     1  ...     1     0   NaN     0   NaN  819
2  1483016  163.0  16.0  104.0  239.0     0  ...     0     0   NaN     0   NaN  803
3   959054    NaN   NaN    NaN  102.0     0  ...     1     0   NaN     0   NaN  530
4  1342113    3.0   2.0    2.0   62.0     0  ...     1     0   NaN     0   NaN  485

[5 rows x 305 columns]

In [10]:
rmv_null = []
for col in credit_train.columns:
  if (credit_train[col].isna().sum()/len(credit_train))*100 > 20:
    rmv_null.append(col)
print(rmv_null)

['x002', 'x003', 'x004', 'x041', 'x057', 'x058', 'x098', 'x148', 'x155', 'x162', 'x222', 'x223', 'x235', 'x237', 'x238', 'x239', 'x242', 'x253', 'x255', 'x256', 'x257', 'x259', 'x265', 'x266', 'x267', 'x268', 'x275', 'x287', 'x288', 'x289', 'x290', 'x293', 'x295', 'x297', 'x302', 'x304']


In [0]:
rmv_null.append('x001')

In [12]:
len(rmv_null)

37

In [0]:
credit_train.drop(columns=rmv_null,axis=1,inplace=True)
credit_test.drop(columns=rmv_null,axis=1,inplace=True)

In [0]:
unq_val = []
for col in credit_train.columns:
  if (credit_train[col].nunique()) == 1:
    unq_val.append(col)

In [0]:
credit_train.drop(columns=unq_val,axis=1,inplace=True)
credit_test.drop(columns=unq_val,axis=1,inplace=True)

In [16]:
for col in credit_train.columns:
   if credit_train[col].isna().sum() > 0:
     print(col,credit_train[col].isna().sum(),(credit_train[col].isna().sum()/len(credit_train))*100)

x005 4867 6.08375
x044 15753 19.69125
x045 15753 19.69125
x234 15316 19.145
x272 5752 7.19


In [0]:
for col in ['x005','x044','x045','x234','x272']:
  rpl = credit_train[col].mean()
  credit_train[col].fillna(rpl,inplace=True)

In [18]:
for col in credit_test.columns:
   if credit_test[col].isna().sum() > 0:
     print(col,credit_test[col].isna().sum(),(credit_test[col].isna().sum()/len(credit_test))*100)

x005 1243 6.215
x044 3921 19.605
x045 3921 19.605
x234 3794 18.970000000000002
x272 1437 7.185


In [0]:
for col in ['x005','x044','x045','x234','x272']:
  rpl = credit_test[col].mean()
  credit_test[col].fillna(rpl,inplace=True)

In [0]:
credit_train.corr()

x005      x006      x007  ...      x301      x303         y
x005  1.000000  0.120654 -0.057133  ... -0.096474 -0.011478  0.561643
x006  0.120654  1.000000 -0.128551  ... -0.005515 -0.009682  0.092552
x007 -0.057133 -0.128551  1.000000  ...  0.002983  0.091289  0.008623
x008 -0.071699 -0.111536  0.813488  ...  0.008644  0.104808 -0.022150
x009 -0.022244 -0.006926  0.268219  ...  0.015378  0.123830 -0.000553
x010  0.025753  0.023741  0.180121  ...  0.021424  0.138753  0.043540
x011  0.097916  0.055588  0.150105  ...  0.074808  0.211842  0.115146
x012  0.124923  0.057186  0.103993  ...  0.207981  0.274163  0.119120
x013  0.192119  0.066786  0.084077  ...  0.203118  0.275521  0.177954
x014  0.601528  0.121001  0.044111  ...  0.019913  0.166601  0.472186
x015  0.353557  0.076078  0.320414  ...  0.122583  0.304279  0.309319
x016  0.191201 -0.113815  0.460539  ...  0.077501  0.392175  0.193854
x017  0.361707  0.155161  0.184448  ...  0.119815  0.197701  0.303187
x018  0.396920  0.160862  0.229369  ...  0.023926  0.149123  0.409353
x019  0.325241 -0.074899  0.354662  ... -0.023316  0.202780  0.411619
x020  0.428496  0.083788  0.292127  ... -0.097379  0.052754  0.415614
x021  0.232651 -0.166315  0.477366  ... -0.066544  0.084721  0.242028
x022  0.455461  0.231601  0.217810  ... -0.105713  0.067454  0.568507
x023  0.362422 -0.136455  0.336537  ... -0.105558  0.070652  0.479607
x024 -0.005363  0.011274  0.212752  ...  0.333977  0.452565 -0.058331
x025  0.447964  0.089307  0.008108  ... -0.123933 -0.007029  0.485231
x026  0.180350  0.064332  0.134019  ... -0.000160  0.081729  0.214605
x027  0.295891  0.387572  0.209645  ... -0.058241  0.087665  0.426141
x028  0.372427  0.071073  0.006512  ... -0.104479 -0.007011  0.412992
x029  0.213022  0.045469  0.130500  ... -0.033425  0.068477  0.215034
x030  0.413070  0.082023  0.258383  ... -0.095691  0.049437  0.426534
x031 -0.197948 -0.008079  0.318792  ...  0.067877  0.066341 -0.280806
x032 -0.075092 -0.024816  0.177789  ...  0.028006  0.021886 -0.077139
x033 -0.105893 -0.035207  0.318809  ...  0.034102  0.029966 -0.113659
x034 -0.156448 -0.039830  0.427335  ...  0.045785  0.038631 -0.192863
...        ...       ...       ...  ...       ...       ...       ...
x262  0.387999  0.066064  0.015159  ... -0.111574 -0.001140  0.443585
x263  0.065558 -0.011583  0.190475  ... -0.000621  0.089727  0.134945
x264  0.070443 -0.023767  0.196525  ... -0.015050  0.078573  0.115324
x269  0.029014  0.004280  0.171136  ...  0.022610  0.090984  0.062783
x270  0.031850  0.006847  0.169570  ...  0.022127  0.090583  0.067566
x271  0.041343  0.011035  0.168085  ...  0.020255  0.091923  0.081103
x272 -0.038474 -0.001040 -0.010906  ... -0.011501  0.000053 -0.067494
x273  0.228328  0.025146  0.044566  ... -0.024636  0.160546  0.232838
x274  0.016843  0.050148 -0.013638  ...  0.069964  0.065323 -0.137094
x276 -0.077921  0.011387  0.070847  ...  0.214247  0.104461 -0.307033
x277 -0.076835  0.011555  0.068590  ...  0.213503  0.120531 -0.308404
x278 -0.077640  0.012116  0.058864  ...  0.215770  0.150214 -0.316125
x279  0.227829  0.021010  0.045543  ... -0.029538  0.159999  0.241753
x280  0.050463  0.024698 -0.000457  ...  0.056849  0.138658 -0.068942
x281  0.222372  0.014924  0.047390  ... -0.046489  0.127413  0.270083
x282  0.132207  0.127419  0.198799  ...  0.013869  0.104114  0.297065
x283  0.117310  0.132943  0.192746  ...  0.017817  0.100704  0.286920
x284  0.098882  0.143160  0.183520  ...  0.027067  0.095994  0.272008
x285 -0.054347 -0.014410  0.223212  ...  0.238893  0.572281 -0.059129
x286 -0.064191  0.029365 -0.000640  ...  0.261538  0.118638 -0.202854
x291  0.048810 -0.012181  0.149317  ...  0.160032  0.703851  0.046320
x292  0.205256  0.024236  0.044383  ... -0.022370  0.170384  0.233451
x294 -0.023020  0.021039  0.015570  ...  0.220346  0.435499 -0.149850
x296  0.061921 -0.021439  0.155772  ...  0.087249  0.592570  0.108856
x298 -0.066023 -0.008745  0.217392  ...  0.145912  0.241759 -0.044734
x299 -0.069295 -0.00

In [0]:
inp_cols = list(credit_train.columns)
inp_cols.remove('y')

In [21]:
print(inp_cols)

['x005', 'x006', 'x007', 'x008', 'x009', 'x010', 'x011', 'x012', 'x013', 'x014', 'x015', 'x016', 'x017', 'x018', 'x019', 'x020', 'x021', 'x022', 'x023', 'x024', 'x025', 'x026', 'x027', 'x028', 'x029', 'x030', 'x031', 'x032', 'x033', 'x034', 'x035', 'x036', 'x037', 'x038', 'x039', 'x040', 'x042', 'x043', 'x044', 'x045', 'x046', 'x047', 'x048', 'x049', 'x050', 'x051', 'x052', 'x053', 'x054', 'x055', 'x056', 'x059', 'x060', 'x061', 'x062', 'x063', 'x064', 'x065', 'x066', 'x068', 'x069', 'x070', 'x071', 'x072', 'x073', 'x074', 'x075', 'x076', 'x077', 'x078', 'x079', 'x080', 'x081', 'x082', 'x083', 'x084', 'x085', 'x086', 'x087', 'x088', 'x089', 'x090', 'x091', 'x092', 'x093', 'x097', 'x099', 'x100', 'x101', 'x102', 'x103', 'x104', 'x105', 'x106', 'x107', 'x108', 'x109', 'x110', 'x111', 'x112', 'x113', 'x114', 'x115', 'x116', 'x117', 'x118', 'x119', 'x120', 'x121', 'x122', 'x123', 'x124', 'x125', 'x126', 'x127', 'x128', 'x129', 'x130', 'x131', 'x132', 'x133', 'x134', 'x135', 'x136', 'x137',

In [22]:
cat_col = []
prt = []
i=0
for col in credit_train.columns:
  cnt = credit_train[col].nunique()
  if cnt > 2 and cnt < 11:
    print(col,i,cnt)
    cat_col.append(i)
    prt.append(col)
  i = i + 1

x022 17 7
x023 18 6
x037 32 5
x049 43 9
x050 44 8
x051 45 8
x052 46 8
x053 47 9
x068 59 7
x077 68 3
x078 69 5
x079 70 9
x107 94 10
x156 141 10
x252 229 4


In [23]:
credit_train[prt].apply(lambda x: print(x.unique()))

[3 0 1 2 4 5 6]
[2 1 0 3 4 5]
[0 1 4 2 3]
[0 1 3 5 2 4 6 7 9]
[0 1 2 3 4 6 5 7]
[0 1 2 3 6 4 5 7]
[0 2 1 3 5 4 7 6]
[0 4 1 2 3 7 5 6 8]
[0 1 3 2 5 8 4]
[0 1 2]
[0 1 2 3 6]
[ 0  1  2  3  4 20  5 11  6]
[0 2 1 4 3 5 7 8 6 9]
[ 0  4  2  1  3  6  5  8  7 11]
[0 1 2 3]


x022    None
x023    None
x037    None
x049    None
x050    None
x051    None
x052    None
x053    None
x068    None
x077    None
x078    None
x079    None
x107    None
x156    None
x252    None
dtype: object

In [24]:
credit_test[prt].apply(lambda x: print(x.unique()))

[2 3 1 0 4 5]
[1 3 2 0 4 5]
[0 1 3 2 4]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5]
[0 1 2 6 3 4 5]
[0 1 2 4 3 5 7]
[0 1 2 3 4 5 8]
[0 1 4 2 3]
[0 1 3 2]
[0 1 2 3 5]
[0 1 3 6 2 4 5]
[0 1 2 3 5 4 7 6]
[0 6 4 2 1 3 7 5 8]
[0 2 1 3]


x022    None
x023    None
x037    None
x049    None
x050    None
x051    None
x052    None
x053    None
x068    None
x077    None
x078    None
x079    None
x107    None
x156    None
x252    None
dtype: object

In [0]:
credit_train['src'] = 0
credit_test['src'] = 1

In [0]:
src = pd.concat([credit_train,credit_test])

In [0]:
src = pd.get_dummies(data=src, columns=prt)

In [0]:
train = src[src['src'] == 0]
test = src[src['src'] == 1]

In [0]:
inp_cols = list(train.columns)
inp_cols.remove('y')
X_train = train[inp_cols]
Y_train = train['y']
X_test = test[inp_cols]
Y_test = test['y']

In [30]:
print(X_train.shape)
print(X_test.shape)

(80000, 359)
(20000, 359)


In [31]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
sel = RandomForestRegressor(n_estimators = 100,random_state=0,n_jobs=-1)
sel.fit(X_train, Y_train)
print(sel.feature_importances_)

[1.35905590e-02 7.72736548e-03 7.20294476e-04 1.26954177e-03
 7.08683027e-04 6.23525916e-04 7.99976701e-04 7.10481076e-04
 7.84169366e-04 6.86944618e-03 2.11131660e-03 7.20116163e-04
 1.84616403e-03 9.69525869e-04 6.12715910e-04 1.98999176e-03
 1.07929306e-03 1.12704240e-03 2.70891818e-04 1.43788838e-04
 8.48558528e-05 6.06539718e-04 5.71509009e-04 1.00700652e-03
 4.39554716e-03 1.93990514e-04 3.55626996e-04 6.27649616e-04
 1.32410005e-03 5.00428200e-03 2.51929208e-04 4.70845311e-04
 1.92749427e-03 1.42912770e-03 5.13170972e-01 2.77289290e-02
 1.67890813e-03 5.13330718e-04 1.60537277e-04 1.34862256e-04
 7.35339728e-04 4.05338907e-02 5.52552563e-02 2.26996985e-03
 1.35241684e-07 9.75112294e-05 2.48725225e-04 4.59964233e-04
 7.56462504e-04 1.38089359e-03 1.58406602e-04 3.70542239e-05
 6.63355669e-05 1.06281240e-04 1.16313575e-04 5.44624620e-04
 1.14755147e-04 7.74462997e-02 4.38728236e-03 3.00813069e-04
 4.41814046e-04 1.06217401e-03 3.34288562e-05 1.69825393e-05
 8.11684037e-05 1.968339

In [0]:
imp = sel.feature_importances_

In [33]:
cntr = 0
pos = []
idx = 0
for value in imp:
  if round(value*1000,4) > 0.05:
    cntr = cntr+1
    pos.append(idx)
  idx = idx + 1
  
print(pos)
print(cntr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 64, 65, 66, 67, 68, 70, 71, 73, 74, 75, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 100, 101, 102, 103, 104, 105, 107, 108, 115, 120, 121, 122, 123, 124, 125, 126, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 249, 250, 251, 252, 257, 258, 262, 263, 

In [0]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [0]:
X_train = X_train.iloc[:,pos]
X_test = X_test.iloc[:,pos]

In [0]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, r2_score

In [0]:
from sklearn import preprocessing
X_train = preprocessing.StandardScaler().fit(X_train).transform(X_train.astype(float))
X_test = preprocessing.StandardScaler().fit(X_test).transform(X_test.astype(float))

In [38]:
X_train.shape

(80000, 233)

In [41]:
from sklearn.linear_model import LinearRegression  
lm = LinearRegression()
lm.fit(X_train,Y_train)
Y_train_predict = lm.predict(X_train)
Y_test_predict = lm.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 51.87440631649835
RMSE Test: 279752636629.16235
MAE Train 39.905836819160825
MAE Test 143944900122.79706


**SVR taking more time -- Need more time to work on SVR**

In [0]:
from sklearn.svm import SVR
SVR = SVR(kernel='linear')
SVR.fit(X_train,Y_train)
Y_train_predict = SVR.predict(X_train)
Y_test_predict = SVR.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))

In [42]:
from sklearn.linear_model import Ridge
ridgeReg = Ridge(alpha=0.005, normalize=False)
ridgeReg.fit(X_train,Y_train)
Y_train_predict = ridgeReg.predict(X_train)
Y_test_predict = ridgeReg.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 51.87444208388783
RMSE Test: 52.36019218061534
MAE Train 39.90549978974659
MAE Test 40.24119355107382


In [43]:
from sklearn.linear_model import Lasso
lassoReg = Lasso(alpha=0.005, normalize=False,max_iter=10000)
lassoReg.fit(X_train,Y_train)
Y_train_predict = lassoReg.predict(X_train)
Y_test_predict = lassoReg.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 51.876696437605034
RMSE Test: 52.34580030719482
MAE Train 39.90824904994285
MAE Test 40.23970145388817


In [44]:
from sklearn.linear_model import ElasticNet
ENreg = ElasticNet(alpha=1, l1_ratio=1, normalize=False)
ENreg.fit(X_train,Y_train)
Y_train_predict = ENreg.predict(X_train)
Y_test_predict = ENreg.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 53.32714804126085
RMSE Test: 53.361325424122825
MAE Train 41.31058024952218
MAE Test 41.39390118376869


**FNN**

In [45]:
from keras.models import Sequential
from keras import optimizers
from keras.layers import Activation, Dense
from keras.layers import Dropout
from keras.layers import BatchNormalization


Using TensorFlow backend.


In [0]:
def mlp_model():
    model = Sequential()
    
    model.add(Dense(50, input_shape = (X_train.shape[1], )))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(50))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(50))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(50))
    model.add(BatchNormalization())                    # Add Batchnorm layer before Activation
    model.add(Activation('elu'))  
    model.add(Dropout(0.2))
    model.add(Dense(1))
    
    adam = optimizers.Adam(lr = 0.001)
    model.compile(optimizer = adam, loss = 'mean_squared_error', metrics=['mse'])
    
    return model

In [47]:
model = mlp_model()
history = model.fit(X_train, Y_train, validation_split = 0.3, epochs = 100, verbose = 1)





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Train on 56000 samples, validate on 24000 samples
Epoch 1/100
56000/56000 [==============================] - 8s 148us/step - loss: 291937.3076 - mean_squared_error: 291937.3076 - val_loss: 142886.4746 - val_mean_squared_error: 142886.4746
Epoch 2/100
56000/56000 [==============================] - 7s 121us/step - loss: 66582.3405 - mean_squared_error: 66582.3405 - val_loss: 9439.0926 - val_mean_squared_error: 9439.0926
Epoch 3/100
56000/56000 [==============================] - 7s 120us/step - loss: 9393.4421 - mean_squared_error: 9393.4421 - val_loss: 4944.5856 - val_mean_squared_error: 4944.5856
Epoch 4/100
56000/56000 [==============================] - 7s 119us/step - loss: 6385.5466 - mean_squared_error: 6385.5466 - val_loss: 3102.6668 - val_mean_squared_error: 3102.6668
Epoch 5/100
56000/56000 [==============================] - 7s 120us/step - loss: 5978.1185 - me

In [48]:
results = model.evaluate(X_test, Y_test)

20000/20000 [==============================] - 1s 27us/step


In [49]:
print(model.metrics_names)     # list of metric names the model is employing
print(results)   

['loss', 'mean_squared_error']
[1393.5197004882812, 1393.5197004882812]


In [50]:
print('loss: ', results[0])
print('mse: ', results[1])

loss:  1393.5197004882812
mse:  1393.5197004882812


**FNN - RMSE = 37**

In [0]:
print('RMSE:',np.sqrt(results[1]))

RMSE: 37.02503651062725


**FNN with Voting Classifier - Stacking**

In [51]:
from sklearn.ensemble import VotingRegressor
from keras.wrappers.scikit_learn import KerasRegressor
# create 5 models to ensemble
model1 = KerasRegressor(build_fn = mlp_model, epochs = 100)
model2 = KerasRegressor(build_fn = mlp_model, epochs = 100)
model3 = KerasRegressor(build_fn = mlp_model, epochs = 100)
model4 = KerasRegressor(build_fn = mlp_model, epochs = 100)
model5 = KerasRegressor(build_fn = mlp_model, epochs = 100)
ensemble_clf = VotingRegressor(estimators = [('model1', model1), ('model2', model2), ('model3', model3), ('model4', model4), ('model5', model5)])
ensemble_clf.fit(X_train, Y_train)
Y_train_predict = ensemble_clf.predict(X_train)
Y_test_predict = ensemble_clf.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

Epoch 1/100
80000/80000 [==============================] - 9s 116us/step - loss: 237285.0661 - mean_squared_error: 237285.0661
Epoch 2/100
80000/80000 [==============================] - 8s 95us/step - loss: 26302.8027 - mean_squared_error: 26302.8027
Epoch 3/100
80000/80000 [==============================] - 8s 94us/step - loss: 6555.3816 - mean_squared_error: 6555.3816
Epoch 4/100
80000/80000 [==============================] - 8s 98us/step - loss: 6017.7425 - mean_squared_error: 6017.7425
Epoch 5/100
80000/80000 [==============================] - 7s 93us/step - loss: 5517.1099 - mean_squared_error: 5517.1099
Epoch 6/100
80000/80000 [==============================] - 7s 92us/step - loss: 5259.9552 - mean_squared_error: 5259.9552
Epoch 7/100
80000/80000 [==============================] - 7s 93us/step - loss: 4957.9074 - mean_squared_error: 4957.9074
Epoch 8/100
80000/80000 [==============================] - 8s 101us/step - loss: 4720.4621 - mean_squared_error: 4720.4621
Epoch 9/100
8000

**FNN - Best Result = 35.66**

In [52]:
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

RMSE Train: 34.25309473907213
RMSE Test: 35.66208756490501
MAE Train 27.06610314025879
MAE Test 28.084395446777343


**RNN**

In [0]:
from keras.layers import LSTM, Bidirectional
from keras.wrappers.scikit_learn import KerasRegressor

def deep_bidirectional_lstm():
    model = Sequential()
    model.add(Bidirectional(LSTM(10, return_sequences = True), input_shape = (233,1)))
    model.add(Bidirectional(LSTM(10, return_sequences = True)))
    model.add(Bidirectional(LSTM(10, return_sequences = True)))
    model.add(Bidirectional(LSTM(10, return_sequences = False)))
    model.add(Dense(46))
    model.add(Activation('elu'))
    model.add(Dense(1))
    
    adam = optimizers.Adam(lr = 0.001)
    model.compile(optimizer = adam, loss = 'mean_squared_error', metrics=['mse'])
    
    return model

In [0]:
X_train = np.array(X_train).reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = np.array(X_test).reshape((X_test.shape[0], X_test.shape[1], 1))

In [0]:
model = KerasRegressor(build_fn = deep_bidirectional_lstm, epochs = 20, batch_size = 1000, verbose = 1)
model.fit(X_train, Y_train)

In [0]:
Y_train_predict = model.predict(X_train)
Y_test_predict = model.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

**Random Forest and KNN - Not as good as deep learning**

In [0]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
sel = RandomForestRegressor()
sel.fit(X_train, Y_train)
Y_train_predict = sel.predict(X_train)
Y_test_predict = sel.predict(X_test)
print("RMSE Train:",np.sqrt(mean_squared_error(Y_train, Y_train_predict)))
print("RMSE Test:",np.sqrt(mean_squared_error(Y_test, Y_test_predict)))
print('MAE Train', mean_absolute_error(Y_train, Y_train_predict))
print('MAE Test', mean_absolute_error(Y_test, Y_test_predict))

In [0]:
from sklearn.neighbors import KNeighborsRegressor

In [41]:
accuracy_dict = {}
accuracy_list = []
for K in range(0,50,5):
    K_value = K + 1
    neigh = KNeighborsRegressor(n_neighbors=K_value,weights='uniform',algorithm='auto')
    neigh.fit(X_train, Y_train)
    y_pred=neigh.predict(X_test)
    accuracy = r2_score(Y_test, y_pred)
    accuracy_dict.update({K_value:accuracy})
    accuracy_list.append(accuracy)
    print("RMSE is",np.sqrt(mean_squared_error(Y_test, y_pred)),"% for K-Value",K_value)

RMSE is 58.53176317180271 % for K-Value 1
RMSE is 47.149524314202324 % for K-Value 6
RMSE is 46.671414455453636 % for K-Value 11
RMSE is 46.75266975373238 % for K-Value 16
RMSE is 47.07537396573293 % for K-Value 21
RMSE is 47.366899257459025 % for K-Value 26
RMSE is 47.583246882941864 % for K-Value 31
RMSE is 47.80396480421981 % for K-Value 36


KeyboardInterrupt: ignored