In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
import numpy as np

In [4]:
!ls 'drive/My Drive/Hackathon/Hackathon/SentimentAnalysis'

review_test.csv  review_train.csv


In [0]:
sent_train = pd.read_csv('drive/My Drive/Hackathon/Hackathon/SentimentAnalysis/review_train.csv')
sent_test = pd.read_csv('drive/My Drive/Hackathon/Hackathon/SentimentAnalysis/review_test.csv')

In [6]:
sent_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14825 entries, 0 to 14824
Data columns (total 3 columns):
Text         14825 non-null object
Score        14825 non-null int64
Sentiment    14825 non-null int64
dtypes: int64(2), object(1)
memory usage: 347.5+ KB


In [7]:
sent_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3707 entries, 0 to 3706
Data columns (total 3 columns):
Text         3707 non-null object
Score        3707 non-null int64
Sentiment    3707 non-null int64
dtypes: int64(2), object(1)
memory usage: 87.0+ KB


In [0]:
sent_train['src'] = 0
sent_test['src'] = 1

In [0]:
src = pd.concat([sent_train,sent_test])

In [10]:
src.head()

Text  Score  Sentiment  src
0  I got a free sample of these once, and now--we...      5          1    0
1  I used to get this Tea when I lived in Washing...      4          1    0
2  This is my all time favorite 'grab and go' sna...      5          1    0
3  This flavor is very good and unexpected.  The ...      4          1    0
4  thrilled to have this assortment as i got the ...      4          1    0

In [11]:
src['Sentiment'].unique()

array([1, 0])

In [12]:
import unicodedata

def remove_accented_chars(text):
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    return text

import re

def remove_special_characters(text, remove_digits=False):
    pattern = r'[^a-zA-Z0-9\s]' if not remove_digits else r'[^a-zA-Z\s]'
    text = re.sub(pattern, '', text)
    return text
  
!pip install contractions
!pip install textsearch
import contractions
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
wnl = WordNetLemmatizer()

def pos_tag_wordnet(tagged_tokens):
    tag_map = {'j': wordnet.ADJ, 'v': wordnet.VERB, 'n': wordnet.NOUN, 'r': wordnet.ADV}
    new_tagged_tokens = [(word, tag_map.get(tag[0].lower(), wordnet.NOUN))
                            for word, tag in tagged_tokens]
    return new_tagged_tokens

def wordnet_lemmatize_text(text):
    tagged_tokens = nltk.pos_tag(nltk.word_tokenize(text))
    wordnet_tokens = pos_tag_wordnet(tagged_tokens)
    lemmatized_text = ' '.join(wnl.lemmatize(word, tag) for word, tag in wordnet_tokens)
    return lemmatized_text
  
def remove_stopwords(text, is_lower_case=False, stopwords=None):
    if not stopwords:
        stopwords = nltk.corpus.stopwords.words('english')
    tokens = nltk.word_tokenize(text)
    tokens = [token.strip() for token in tokens]
    
    if is_lower_case:
        filtered_tokens = [token for token in tokens if token not in stopwords]
    else:
        filtered_tokens = [token for token in tokens if token.lower() not in stopwords]
    
    filtered_text = ' '.join(filtered_tokens)    
    return filtered_text

     |████████████████████████████████| 317kB 4.9MB/s 
     |████████████████████████████████| 245kB 48.9MB/s 
  Created wheel for pyahocorasick: filename=pyahocorasick-1.4.0-cp36-cp36m-linux_x86_64.whl size=81700 sha256=6967c93cce4269713908f81a7958b3b5fe1d3dd179c34dd4c3c930e6f7fb9aff
  Stored in directory: /root/.cache/pip/wheels/0a/90/61/87a55f5b459792fbb2b7ba6b31721b06ff5cf6bde541b40994
Successfully built pyahocorasick
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [0]:
col = 'Text'
src[col] = src[col].map(lambda x: str(x).lower())
src[col] = src[col].map(lambda x: remove_accented_chars(x))
src[col] = src[col].map(lambda x: remove_special_characters(x))
src[col] = src[col].map(lambda x: contractions.fix(x))
src[col] = src[col].map(lambda x: wordnet_lemmatize_text(x))
src[col] = src[col].map(lambda x: remove_stopwords(x,True))

In [14]:
src

Text  Score  Sentiment  src
0     get free sample nowwere subscribe save program...      5          1    0
1     use get tea live washington state miss niece t...      4          1    0
2     time favorite grab go snack bar leave sugar ru...      5          1    0
3     flavor good unexpected flavor cheese garlic go...      4          1    0
4     thrill assortment get chance choose another de...      4          1    0
5     love flavor coffee drawback set large cup want...      4          1    0
6     like last review mixture dog 2 chihuahua eat a...      5          1    0
7     wonderful handy product I thrill yummy way use...      5          1    0
8     great value sure place bag crowd transfer hard...      5          1    0
9     like flavor kind reminds jello pudding bite th...      4          1    0
10    great product quick shipment place could find ...      5          1    0
11    order parent come back trip vienna rave vienna...      4          1    0
12    natural treat favorite crew price great free s...      5          1    0
13    good last next thing know go everyone family l...      5          1    0
14    great alternative coffee I try vanilla nut als...      5          1    0
15    fruit slice deliver sugar coating melt away ru...      1          0    0
16    provide description productbr br yesterday sho...      4          1    0
17    love dr pepper mr pip even like walmart brandd...      1          0    0
18    mother know divinity love say nut top divinity...      5          1    0
19    great deal delicious lowcal guiltfree treat wr...      5          1    0
20    bbq favorite flavor popchipsbr br popchips hea...      5          1    0
21    receive package time specify good condition he...      5          1    0
22    whole wheat oven ready noodle could find organ...      5          1    0
23    get fast taste like expect exactly every goji ...      5          1    0
24    work real well since unable find maxwell decaf...      5          1    0
25    husband surprise christmas favorite candy avai...      5          1    0
26    stuff good seriously almost eat know people sa...      5          1    0
27    love cereal look forward try since like variet...      5          1    0
28    love bar flavor favorite like option subscribe...      5          1    0
29    soft cooky vert good try oatmeal rasin soft co...      5          1    0
...                                                 ...    ...        ...  ...
3677  product help keep mood stressful time promote ...      5          1    1
3678  son eat breakfast every morning seem really en...      5          1    1
3679  like ginger product fine merit however sushi p...      1          0    1
3680  excellent coffee bold taste great aroma fill e...      5          1    1
3681  knorr shrimp bouillon cube irreplaceable sea f...      5          1    1
3682  flavor disappointed buy base review waste mone...      2          0    1
3683  make 1st child food use pot boil water steam b...      5          1    1
3684  make killer sloppy joes stuff soak mix usual r...      5          1    1
3685  great taste great aroma love sprinkle tablespo...      5          1    1
3686  send french roast favorite mine coffee adverti...      2          0    1
3687  span classtiny length 117 minsbr br spansee vi...      4          1    1
3688  use product year live reputation bed relax hel...      5          1    1
3689  buy bc felt sinus infection creep mespring all...      5          1    1
3690  baby toddler love baby food taste food enjoy t...      5          1    1
3691  extra bold hint flavour strong solid highpoint...      4          1    1
3692  read direction cooky think wow go lot cooky wo...      5          1    1
3693  long time lover dunkin donut ground coffee hes...      5          1    1
3694  really good popcorn kernel pop per batch handy...      4          1    1
3695  love diet big red plain simple one favorite pa...      5          1    1
3696  try coffee day a

In [0]:
train = src[src['src'] == 0]
test = src[src['src'] == 1]

**Dont use score below example use score and predicts 100%**

In [0]:
X_train = train[['Score','src']]
Y_train = train['Sentiment']
X_test = test[['Score','src']]
Y_test = test['Sentiment']

In [0]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn import feature_selection
from sklearn import model_selection
from sklearn import metrics
from sklearn.metrics import classification_report

In [45]:
from sklearn import  linear_model
mdl = linear_model.LogisticRegressionCV()
mdl.fit(X_train,Y_train)
Y_pred=mdl.predict(X_test)
print(metrics.confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test, Y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


[[ 592    0]
 [   0 3115]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       592
           1       1.00      1.00      1.00      3115

    accuracy                           1.00      3707
   macro avg       1.00      1.00      1.00      3707
weighted avg       1.00      1.00      1.00      3707



In [0]:
X_train = train['Text']
Y_train = train['Sentiment']
X_test = test['Text']
Y_test = test['Sentiment']

In [0]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from xgboost import XGBClassifier
#grid search result

In [0]:
vectorizer = TfidfVectorizer(ngram_range=(1,2),min_df=5,max_df=1.0,use_idf=True, sublinear_tf=True) 
counts = vectorizer.fit_transform(X_train)
vocab = vectorizer.vocabulary_
classifier = SGDClassifier(alpha=1e-05,max_iter=50,penalty='elasticnet')
targets = Y_train
classifier = classifier.fit(counts, targets)
example_counts = vectorizer.transform(X_test)
Y_pred = classifier.predict(example_counts)

In [63]:
print(metrics.confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test, Y_pred))

[[ 383  209]
 [ 142 2973]]
              precision    recall  f1-score   support

           0       0.73      0.65      0.69       592
           1       0.93      0.95      0.94      3115

    accuracy                           0.91      3707
   macro avg       0.83      0.80      0.82      3707
weighted avg       0.90      0.91      0.90      3707



In [0]:
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process
from xgboost import XGBClassifier

In [65]:
for mdl in [ensemble.AdaBoostClassifier(),tree.DecisionTreeClassifier(),XGBClassifier(),naive_bayes.BernoulliNB()]:
   classifier = mdl  
   targets = Y_train
   classifier = classifier.fit(counts, targets)
   example_counts = vectorizer.transform(X_test)
   Y_pred = classifier.predict(example_counts)
   print(mdl.__class__.__name__) 
   print(metrics.confusion_matrix(Y_test,Y_pred))
   print(classification_report(Y_test, Y_pred))

AdaBoostClassifier
[[ 234  358]
 [  84 3031]]
              precision    recall  f1-score   support

           0       0.74      0.40      0.51       592
           1       0.89      0.97      0.93      3115

    accuracy                           0.88      3707
   macro avg       0.82      0.68      0.72      3707
weighted avg       0.87      0.88      0.87      3707

DecisionTreeClassifier
[[ 291  301]
 [ 292 2823]]
              precision    recall  f1-score   support

           0       0.50      0.49      0.50       592
           1       0.90      0.91      0.90      3115

    accuracy                           0.84      3707
   macro avg       0.70      0.70      0.70      3707
weighted avg       0.84      0.84      0.84      3707

XGBClassifier
[[ 126  466]
 [  14 3101]]
              precision    recall  f1-score   support

           0       0.90      0.21      0.34       592
           1       0.87      1.00      0.93      3115

    accuracy                           0.87  

**************************Code below are in progress need more time to complete** 

**Word2Vec Model**

In [17]:
import nltk
from gensim.models import word2vec

tokenized_corpus = [nltk.word_tokenize(doc) for doc in list(src['Text'])]

# Set values for various parameters
feature_size = 25    # Word vector dimensionality  
window_context = 20  # Context window size                                                                                    
min_word_count = 1   # Minimum word count                        
sample = 1e-3        # Downsample setting for frequent words
sg = 1               # skip-gram model

w2v_model = word2vec.Word2Vec(tokenized_corpus, size=feature_size, 
                              window=window_context, min_count = min_word_count,
                              sg=sg, sample=sample, iter=10)
w2v_model

In [20]:
w2v_model

In [22]:
w2v_model['great']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.23662362, -0.05379179,  0.01059656, -0.09407976, -0.4382522 ,
       -0.01218937, -0.5350406 ,  0.00562505,  0.19398579,  0.667377  ,
        0.3784096 , -0.1620181 , -0.01792208,  1.1302689 , -0.1320794 ,
        0.14009635,  0.12492268, -0.2001968 ,  0.66609013, -0.38946134,
        0.08393219,  0.21517958, -0.36435458, -0.19027226,  0.4639255 ],
      dtype=float32)

In [23]:
import matplotlib.pyplot as plt

%matplotlib inline

# visualize embeddings
from sklearn.manifold import TSNE

words = w2v_model.wv.index2word
wvs = w2v_model.wv[words]

tsne = TSNE(n_components=2, random_state=42, n_iter=5000, perplexity=5)
np.set_printoptions(suppress=True)
T = tsne.fit_transform(wvs)
labels = words

plt.figure(figsize=(12, 6))
plt.scatter(T[:, 0], T[:, 1], c='orange', edgecolors='r')
for label, x, y in zip(labels, T[:, 0], T[:, 1]):
    plt.annotate(label, xy=(x+1, y+1), xytext=(0, 0), textcoords='offset points')

KeyboardInterrupt: ignored

In [30]:
vec_df = pd.DataFrame(wvs, index=words)
vec_df.T

like        br      good  ...     mgsan   cuginos  mealtype
0  -0.253746 -0.023921 -0.125472  ... -0.251431 -0.304721 -0.200947
1  -0.228368 -0.203169 -0.119185  ... -0.031203 -0.212731 -0.324006
2   0.162058  0.201160  0.002860  ...  0.693048  0.319443  0.244928
3  -0.073390 -0.041289 -0.117190  ... -0.149237  0.062054  0.132828
4  -0.361206 -0.020993 -0.250892  ... -0.231033 -0.115816 -0.119373
5  -0.299071 -0.131612 -0.097467  ... -0.201480 -0.105838 -0.236281
6  -0.023418  0.016733 -0.279115  ... -0.222635 -0.257140 -0.233754
7  -0.128880 -0.317871 -0.167142  ... -0.298621 -0.049449 -0.000813
8   0.232743  0.129317  0.251888  ... -0.003542  0.034318 -0.011417
9   0.861466  0.493640  0.838138  ...  0.533152  0.508293  0.633234
10 -0.026261  0.050423  0.109180  ... -0.215210  0.066313  0.190951
11  0.217326  0.018860 -0.105918  ... -0.381756 -0.221735 -0.394782
12  0.050465 -0.134161  0.027245  ... -0.079712  0.105050  0.214680
13  0.964225  0.547413  0.938627  ...  0.450565  0.357592  0.586426
14 -0.052679 -0.182596 -0.082903  ... -0.306139 -0.134170 -0.101839
15 -0.471473 -0.376083 -0.144395  ...  0.010635 -0.061326 -0.104546
16  0.114150 -0.309558  0.121664  ... -0.101323  0.191442  0.237007
17 -0.228058 -0.105306 -0.268856  ... -0.119984 -0.020392 -0.062019
18  0.372070  0.749034  0.531737  ...  0.865394  0.667977  0.870461
19 -0.045168  0.182275 -0.149365  ...  0.183854  0.196560  0.075007
20  0.035384  0.088154  0.118608  ...  0.023239 -0.003028 -0.072822
21  0.075517  0.395425  0.223743  ...  0.417274  0.226862  0.252795
22 -0.168842  0.103090 -0.181775  ...  0.116713  0.026796 -0.041447
23 -0.473160 -0.033588 -0.291070  ...  0.085654 -0.130660 -0.192459
24  0.668037  0.501018  0.550301  ...  0.164691  0.186682  0.265697

[25 rows x 32984 columns]

In [0]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(vec_df.values)
similarity_df = pd.DataFrame(similarity_matrix, index=words, columns=words)
similarity_df

In [18]:
!python -m spacy download en

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/lib/python3.6/dist-packages/en_core_web_sm -->
/usr/local/lib/python3.6/dist-packages/spacy/data/en
You can now load the model via spacy.load('en')


In [19]:
!python -m spacy download en_vectors_web_lg

     |████████████████████████████████| 661.8MB 120.0MB/s 
  Created wheel for en-vectors-web-lg: filename=en_vectors_web_lg-2.1.0-cp36-none-any.whl size=663461749 sha256=f9f8522db7fe46fd8eca714939e3d7d5a446e31d467cbf7e282939e8209fc23a
  Stored in directory: /tmp/pip-ephem-wheel-cache-v52hr5jz/wheels/ce/3e/83/59647d0b4584003cce18fb68ecda2866e7c7b2722c3ecaddaf
Successfully built en-vectors-web-lg
✔ Download and installation successful
You can now load the model via spacy.load('en_vectors_web_lg')


In [26]:
import spacy

nlp = spacy.load('en_vectors_web_lg')
total_vectors = len(nlp.vocab.vectors)

print('Total word vectors:', total_vectors)

OSError: ignored

In [25]:
unique_words = list(set([word for sublist in tokenized_corpus for word in sublist]))

word_glove_vectors = np.array([nlp(word).vector for word in unique_words])
vec_df = pd.DataFrame(word_glove_vectors, index=unique_words)
vec_df

NameError: ignored